[server]
runOnSave = true
headless = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
# backgroundColor="#FFFFFF"
# primaryColor=
# secondaryBackgroundColor =
font = "sans serif"

[logger]
enableRich = true
