[server]
runOnSave = true
headless = true
port = 7001

[browser]
gatherUsageStats = false

[theme]
base = "light"
# backgroundColor="#FFFFFF"
# primaryColor=
# secondaryBackgroundColor =
font = "sans serif"

[logger]
enableRich = true
